version: '3.7'

x-php:
  &php
  build:
    args:
      PHP_VERSION: ${PHP_VERSION:-8.0}
  env_file:
  - .env
  volumes:
  - ./:/app:delegated
  - ~/.composer/cache:/composer/cache:delegated
  networks:
  - panther

services:
  php:
    <<: *php

  ready:
    image: jwilder/dockerize
    networks:
    - panther

  test-webserver:
    <<: *php
    command: [ "php", "-dvariables_order=EGPCS", "-S", "0.0.0.0:9080", "-t", "/app/tests/public" ]
    ports:
    - "9080:9080"

networks:
  panther:
