---
name: Continuous Integration

on:
  pull_request:

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
        - '8.0'
        - '8.1'
        deps:
        - "--prefer-stable"
        - "--prefer-lowest"
    env:
      PHP_VERSION: ${{ matrix.php }}
    steps:
    - uses: actions/checkout@v3
    - uses: styfle/cancel-workflow-action@0.9.1
    - name: Setup Composer cache
      uses: actions/cache@v2.1.7
      with:
        path: vendor
        key: |
          composer-${{ hashFiles('composer.json') }}
          composer-
    - run: make install
    - name: Code style
      if: ${{ matrix.php == '8.0' && matrix.deps == '--prefer-stable' }}
      run: make cs-check
    - name: Static analysis
      if: ${{ matrix.php == '8.0' && matrix.deps == '--prefer-stable' }}
      run: make phpstan
    - name: Test suite
      run: make test
